### ISSUE TITLE
Apples to Apples v Round 1

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/real_estate#17]
@cloef another thing I wanted to mention, I think it's important to try and understand why Peer didn't come out significant this time to whatever extent that we can--there's rather less general insights we can offer from our experiments if the things that work vary from year to year, population to population in a way that we don't understand.

One idea from our meeting w Marisa today is to perhaps re-run the first round tests on _only_ properties owing exactly 1 year of debt.

**Comment by cloef** [comment]
Mike,
I agree. Started putting together a slide on that topic. Your suggestion on
the 1 year of debt only properties from round 1 is a good one. I think the
other thing to consider is running lien, peer, and baseline again in a
couple months to see whether either of these have effects on persistently
late folks.
Best,
Charles

**Comment by MichaelChirico** [comment]
@cloef Here's the results of the basic regression we in Round 1 (i.e., property-level logistic vs. treatment only) on R2 data:

```
Coefficients:
                      Estimate Std. Error t value Pr(>|t|)    
(Intercept)          0.3017169  0.0078410  38.479  < 2e-16 ***
main_treatAmenities  0.0107658  0.0110428   0.975 0.329609    
main_treatMoral      0.0103481  0.0111730   0.926 0.354367    
main_treatDuty      -0.0003591  0.0112231  -0.032 0.974473    
main_treatLien       0.0482546  0.0111260   4.337 1.45e-05 ***
main_treatSheriff    0.0445509  0.0112333   3.966 7.33e-05 ***
main_treatPeer       0.0385198  0.0112299   3.430 0.000604 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

Note that I am not using clustered errors. So Peer = Civic Duty comes out significant & positive, but the magnitude of the coefficient is quite different (it was .21 in round 1).

Also there's absolutely nothing for paid in full, and the effect is if anything weaker when we focus on sole owners.

So not quite ready to close the book on this yet.

**Comment by MichaelChirico** [comment]
In meeting on November 3rd, team mentioned doing some sort of propensity score matching approach to get a better comparison of Round 1 & Round 2 properties.
