### ISSUE TITLE
Financial analyses

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/real_estate#18]
Perform some analyses to probe the fiscal efficacy of our experiment.

Examples that come to mind:
- [x] Total money received by treatment
- [x] Total money received above control
- [x] Total money received above holdout
- [x] Total money received by envelope vs. cost
- [x] Spatial version: total money received by neighborhood / quadrant for each of the above (assigned here instead of #15)

**Comment by MichaelChirico** [comment]
Check 1 covered by table corresponding to Table 4 in the first round paper; Checks 2 & 3 covered by histograms with confidence intervals of surplus distribution.

**Comment by MichaelChirico** [comment]
@cloef Check out the following graphs which are interesting if only because our lead treatments play only a very minor role in all three.

[map_best_trt_avg_pos_paid_sep_7_prop.pdf](https://github.com/MichaelChirico/real_estate/files/35069/map_best_trt_avg_pos_paid_sep_7_prop.pdf)
[map_best_trt_med_pos_paid_sep_7_prop.pdf](https://github.com/MichaelChirico/real_estate/files/35070/map_best_trt_med_pos_paid_sep_7_prop.pdf)
[map_best_trt_prop_debt_paid_sep_7_prop.pdf](https://github.com/MichaelChirico/real_estate/files/35071/map_best_trt_prop_debt_paid_sep_7_prop.pdf)

**Comment by cloef** [comment]
Need more accompanying information to make sense of these. Could you add a
wiki or something with links to each graph?

**Comment by MichaelChirico** [comment]
@cloef You're seeing the graphs, right?

[Here](https://github.com/MichaelChirico/real_estate/wiki) is a little bit of a write-up on what's going into each graph, let me know if that helps.
