### ISSUE TITLE
Add Confidence Intervals (or similar) to Predicted Repayment Rate by Amount Due

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/real_estate#8]
not clear that confidence intervals won't clutter the image beyond usability; anyway, need to explore options for depicting natural variance in this plot if it's going to be interpretable

**Comment by cloef** [comment]
If you decrease the range on the Y access, won't there be room for CIs?

**Comment by MichaelChirico** [comment]
Don't think so, at least without losing a lot of information from the right side of the plot. I'll see how wide the confidence intervals are and keep thinking of workarounds

**Comment by MichaelChirico** [comment]
I'm not sure what CIs look like here. Here's what I'm working on:
1. Resample `BB` times from control group properties; for each sample:
2. Re-fit logit model (`ever_paid` vs. `log(total_due)`)
3. Predict probability of repayment for all in-range debt levels
4. Lower limit of CI is the .025 quantile envelope of those points--i.e., at (log) debt level `x`, the lower limit `y_l` is such that 97.5% of the `BB` predicted probabilities exceed `y_l`; the upper limit is defined similarly

@cloef Let me know if you have opinions on this

**Comment by MichaelChirico** [comment]
First pass here:

![asdf](https://cloud.githubusercontent.com/assets/7606389/9291033/5b6f9bec-4378-11e5-8a35-bea9a8c39132.png)

**Comment by cloef** [comment]
What about not trying to do all the treatments on one graph? So control and
treatment 1 and then do six panes? Good for the appendix of the paper.

**Comment by MichaelChirico** [comment]
Updated versions:

![1](https://cloud.githubusercontent.com/assets/7606389/9321498/5ab0f2d2-4535-11e5-9f63-dbb2e638c7a0.png)
![2](https://cloud.githubusercontent.com/assets/7606389/9321497/5ab0db80-4535-11e5-898d-756bdfd2ac25.png)

The middle panel is too wide, relatively, but I'll kick this down the priority list if it's going to be relegated to the appendix

**Comment by cloef** [comment]
Thanks. This can go down the priority list.

**Comment by MichaelChirico** [comment]
Turns it out it was an easy fix, so I just took care of it while it's fresh; plots added to drive & box
