### ISSUE TITLE
Add plot to illustrate distribution of payments by treatment

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/real_estate#9]
Beyond average payment by treatment, we should try and depict the distribution of payments; the problem with simple box-and-whiskers here is the huge mass at 0 in all groups (no treatment has less than 60% of the sample paying $0)

Possible representations:
- Average paid by payers, with bootstrapped confidence intervals (sort of treatment on the treated)
- Median paid by payers, with bootstrapped confidence intervals
- Box-and-whisker plot of distribution among payers, with notch (should be parametric/asymptotic) confidence intervals around the median

**Comment by cloef** [comment]
Having bw among payers provides the most information. It's a bit hard for
some folks to understand. What about smoothed density curves? Should be
more small payments among the lien/sheriff treatments.

**Comment by MichaelChirico** [comment]
Merging this with #11 due to 100% overlap
